"""The two Section III diagrams, emitted as TikZ.

TikZ rather than a raster: the labels then set in the document's own serif face
at the document's own size, the rules are true hairlines, and the figure scales
with the column rather than against it.

Every parameter in both diagrams is read from the deployed dataclasses, so the
figures cannot drift from the configuration that flew. `audit_claims` checks the
same constants against the results sections that measure them.

    python -m tello_gesture_py.src.gestures.build_design_figures
"""

import argparse
import io
import os

from ..config import ControllerConfig
from ..face_follow import FaceFollowConfig

PREAMBLE = r"""% Generated by tello_gesture_py/src/gestures/build_design_figures.py
% Do not edit: every value here is read from the deployed configuration.
"""

STYLES = r"""
\tikzset{
  blk/.style   = {draw, line width=0.4pt, inner sep=3pt, align=center,
                  minimum height=6.5mm, font=\scriptsize},
  wide/.style  = {blk, text width=20mm},
  narrow/.style= {blk, text width=17mm},
  gate/.style  = {wide, fill=black!4},
  aux/.style   = {wide, draw=black!35, text=black!55},
  flow/.style  = {-{Stealth[length=1.6mm,width=1.4mm]}, line width=0.4pt},
  aside/.style = {flow, densely dashed, draw=black!55},
  lbl/.style   = {font=\fontsize{6}{7}\selectfont, inner sep=1.5pt},
  grp/.style   = {draw=black!25, line width=0.3pt, rounded corners=1pt,
                  inner sep=0pt},
}
"""


def architecture(cfg, fcfg):
    """Sensor/actuator node on the left, host pipeline on the right."""
    L = [PREAMBLE, r"\begin{tikzpicture}[x=1mm,y=1mm]", STYLES, ""]
    A = L.append

    TOP, BOT = 7.5, -7.5      # the two pipeline rows
    JOIN = 122                # shared vertical where the branches merge

    # --- aircraft ---------------------------------------------------------
    A(r"\node[blk, text width=25mm, minimum height=34mm] (air) at (0,0)"
      r" {DJI Tello EDU\\[3pt]"
      r"\fontsize{6}{7.5}\selectfont camera\\ IMU, barometer\\ motors};")
    A(r"\node[lbl, above=1.2mm of air] {\textsc{aircraft}};")

    # --- host -------------------------------------------------------------
    A(r"\node[grp, fit={(38,-19) (177,17)}] (host) {};")
    A(r"\node[lbl, above=0.6mm of host.north] {\textsc{host}};")

    A(r"\node[wide] (buf) at (52,%.1f) {latest-frame buffer\\"
      r"\fontsize{6}{7}\selectfont thread, depth 1};" % TOP)
    A(r"\node[narrow] (hand) at (79,%.1f) {MediaPipe Hands\\"
      r"\fontsize{6}{7}\selectfont every %dnd frame};" % (TOP, cfg.hand_every_n))
    A(r"\node[narrow] (face) at (79,%.1f) {MediaPipe face\\"
      r"\fontsize{6}{7}\selectfont every %dth frame};" % (BOT, cfg.face_every_n))
    A(r"\node[narrow] (clf) at (105,%.1f) {gesture classifier\\"
      r"\fontsize{6}{7}\selectfont rule \textbar{} RBF-SVM};" % TOP)
    A(r"\node[narrow, fill=black!5] (gate) at (105,%.1f) {identity gate\\"
      r"\fontsize{6}{7}\selectfont $\tau_{\mathrm{on}}{=}%s$,"
      r" $\Delta_{\max}{=}%s$\,s};"
      % (BOT, cfg.faceid_cosine_thr, fcfg.crop_max_age_s))
    # No cross-reference here: the short paper carries no state-machine figure,
    # and a \ref to a label it lacks would break its build.
    A(r"\node[narrow, fill=black!5] (fsm) at (136,0) {arbitration\\"
      r"\fontsize{6}{7}\selectfont priority order};")
    A(r"\node[narrow] (rc) at (163,0) {RC command\\"
      r"\fontsize{6}{7}\selectfont %d\,Hz};" % round(1.0 / cfg.rc_dt))
    # Sits above the control path, never on it: the model receives each decision
    # after it is taken and returns a sentence for the log.
    A(r"\node[aux, text width=22mm] (llm) at (136,12.5) {reason-only LLM\\"
      r"\fontsize{6}{7}\selectfont local %s};"
      % cfg.llm_model.replace("qwen2.5:0.5b-instruct", "Qwen2.5-0.5B"))

    # --- inbound channels -------------------------------------------------
    # Both labels sit at the same x so the two channels read as a pair.
    LBLX = 25.8
    A(r"\draw[flow] (air.east |- buf) -- (buf.west);")
    A(r"\node[lbl, above=0.3mm] at (%.2f,%.1f) {video};" % (LBLX, TOP))
    A(r"\node[lbl, below=0.3mm] at (%.2f,%.1f) {UDP %d};"
      % (LBLX, TOP, cfg.video_port))

    # --- the two rows, all segments axis-aligned --------------------------
    A(r"\draw[flow] (buf.east) -- (hand.west);")
    A(r"\draw[flow] (hand.east) -- (clf.west);")
    A(r"\draw[flow] (buf.south) -- (52,%.1f) -- (face.west);" % BOT)
    A(r"\draw[flow] (face.east) -- (gate.west);")

    # --- both branches merge on one vertical, then enter one face ---------
    A(r"\draw[line width=0.4pt] (clf.east) -- (%d,%.1f);" % (JOIN, TOP))
    A(r"\draw[line width=0.4pt] (gate.east) -- (%d,%.1f);" % (JOIN, BOT))
    A(r"\draw[line width=0.4pt] (%d,%.1f) -- (%d,%.1f);" % (JOIN, TOP, JOIN, BOT))
    A(r"\draw[flow] (%d,0) -- (fsm.west);" % JOIN)
    A(r"\fill (%d,0) circle (0.45);" % JOIN)

    A(r"\draw[flow] (fsm.east) -- (rc.west);")
    A(r"\draw[aside] (fsm.north) -- (llm.south);")

    # Telemetry is read by the battery failsafe, so it lands on arbitration.
    A(r"\draw[flow] (air.east |- 0,-15) -- (136,-15) -- (fsm.south);")
    A(r"\node[lbl, above=0.3mm] at (%.2f,-15) {telemetry};" % LBLX)
    A(r"\node[lbl, below=0.3mm] at (%.2f,-15) {UDP %d};"
      % (LBLX, cfg.state_port))

    # --- command out ------------------------------------------------------
    A(r"\draw[flow] (rc.east) -- (183,0) -- (183,-25) --"
      r" node[lbl, pos=0.42, above=0.3mm] {command}"
      r" node[lbl, pos=0.42, below=0.3mm] {UDP %d}"
      r" (0,-25) -- (air.south);" % cfg.cmd_port)

    A(r"\end{tikzpicture}")
    return "\n".join(L) + "\n"


def hfsm(cfg):
    """Priority order top to bottom; one mode selected per control tick."""
    L = [PREAMBLE, r"\begin{tikzpicture}[x=1mm,y=1mm]", STYLES, ""]
    A = L.append

    rows = [
        (r"\textsc{land}", r"battery $\le %d\%%$" % cfg.battery_land_pct),
        (r"\textsc{gesture}", r"authorized hand present"),
        (r"\textsc{face}", r"authorized face present"),
        (r"\textsc{search}", r"nothing seen for %d\,s" % round(cfg.nohuman_search_s)),
        (r"\textsc{hover}", r"otherwise"),
    ]
    dy = 7.0
    for i, (mode, cond) in enumerate(rows):
        y = -i * dy
        A(r"\node[blk, text width=20mm, minimum height=%.1fmm, anchor=north west,"
          r" fill=%s] (m%d) at (0,%.1f) {%s};"
          % (dy, "black!6" if i == 0 else "white", i, y + dy / 2, mode))
        A(r"\node[font=\scriptsize, anchor=west] at (23,%.1f) {%s};"
          % (y, cond))

    A(r"\draw[flow, draw=black!45] (-3.5,%.1f) -- (-3.5,%.1f)"
      r" node[lbl, midway, rotate=90, anchor=south, text=black!45]"
      r" {evaluated in order, each tick};"
      % (dy / 2 - 0.5, -(len(rows) - 1) * dy - dy / 2 + 0.5))

    A(r"\node[lbl, text width=44mm, anchor=north west, align=left]"
      r" at (0,%.1f) {A mode is held for at least %s\,s and released once its"
      r" signal has been absent for %s\,s. The sweep runs %d\,s, one full"
      r" rotation at the configured yaw rate, then a %d\,s cooldown.};"
      % (-(len(rows) - 1) * dy - dy / 2 - 2, cfg.mode_hold_s,
         cfg.hand_release_s, round(cfg.search_duration_s),
         round(cfg.search_cooldown_s)))

    A(r"\end{tikzpicture}")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="paper/figures")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    cfg, fcfg = ControllerConfig(), FaceFollowConfig()
    for name, body in (("fig_architecture.tex", architecture(cfg, fcfg)),
                       ("fig_hfsm.tex", hfsm(cfg))):
        p = os.path.join(a.outdir, name)
        io.open(p, "w", encoding="utf-8", newline="\n").write(body)
        print("wrote", p)


if __name__ == "__main__":
    main()
